// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIk6393wM2TCD4QBwll9kEX1cFTlW8mE',
    appId: '1:559037294917:web:da89449881886b3f47b62c',
    messagingSenderId: '559037294917',
    projectId: 'dukka-2f863',
    authDomain: 'dukka-2f863.firebaseapp.com',
    storageBucket: 'dukka-2f863.appspot.com',
    measurementId: 'G-VHE7GSGWBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyOZK3wCr_2H5mtM8lNCaEjFbJr4zXw4',
    appId: '1:559037294917:android:b9830d902bf1b25247b62c',
    messagingSenderId: '559037294917',
    projectId: 'dukka-2f863',
    storageBucket: 'dukka-2f863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxT88I4FUJqGj61OTF6eJelej0fMqO-8s',
    appId: '1:559037294917:ios:45a5bc88c0ab3bf347b62c',
    messagingSenderId: '559037294917',
    projectId: 'dukka-2f863',
    storageBucket: 'dukka-2f863.appspot.com',
    iosClientId: '559037294917-a5444lp7p4824nvvaod718o0p3u6no2k.apps.googleusercontent.com',
    iosBundleId: 'com.dukka.app',
  );
}
